# Generated by Django 4.2.11 on 2024-09-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_links_link_rename_projects_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='webqr',
            field=models.ImageField(default='', upload_to='profile'),
            preserve_default=False,
        ),
    ]
