# Generated by Django 4.2.11 on 2024-09-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_education_to_date_alter_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='score_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('GPA', 'GPA')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='score',
            field=models.FloatField(),
        ),
    ]
