# Generated by Django 5.1 on 2024-09-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_education_score_type_alter_education_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
